version: '3.3'
services:
    solr:
        container_name: solr
        image: 'solr:8.5.2'
        ports:
            - '8983:8983'
        volumes:
            # - ./data:/SWE-599/solr/server/solr/nutch
            - ./nutch-conf/schema.xml:/opt/solr/server/solr/configsets/_default/conf/schema.xml
            - ./nutch-conf/managed-schema:/opt/solr/server/solr/configsets/_default/conf/managed-schema
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - nutch
        environment:
            JVM_OPTS: >
                -XX:-UseLargePages
        networks:
            - be
    nutch:
        container_name: nutch
        image: 'apache/nutch:latest'
        links:
            - solr
        environment:
            - JAVA_HOME=/usr/lib/jvm/java-11-openjdk
        working_dir: /root/nutch
        command: '/root/nutch/bin/nutch startserver -port 8081 -host localhost'
        volumes:
            - ./nutch-conf/index-writers.xml:/root/nutch/conf/index-writers.xml
            - ./nutch-conf/nutch-site.xml:/root/nutch/conf/nutch-site.xml
            - ./nutch-conf/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt
            - ./nutch-conf/seed.txt:/root/nutch/urls/seed.txt
        depends_on:
            - solr
        networks:
            - be
networks:
    be: {}
